services:
  - name: Website
    description: The main website for Tornado Emergency.
    url: https://tornadoemergency.net
    hide_url: false
    expected_response_code: 200
  - name: TM API Services
    description: The API for Tornado Emergency.
    url: https://timmygstudios.com
    hide_url: true
    expected_response_code: 200
data_retention_hours: '24'
check_interval_minutes: '15'
secret: supersecretkey
