services:
  - name: Website
    description: The main website for Tornado Emergency.
    url: https://tornadoemergency.net
    hide_url: false
    expected_response_code: 200
  - name: API
    description: The API for Tornado Emergency.
    url: https://timmygstudios.com
    hide_url: true
    expected_response_code: 200
  - name: Broken test
    description: The API for Tornado Emergency.
    url: https://timmygsteeeudios.com
    hide_url: true
    expected_response_code: 200

data_retention_days: 30
check_interval_seconds: 300
