categories:
  - name: Web Services
    description: Main web-facing services for Tornado Emergency
    services:
      - &ref_0
        name: TM API Services
        description: The API for Tornado Emergency.
        url: https://timmygstudios.com
        hide_url: true
        expected_response_code: 200
  - name: Test
    description: Test category
    services:
      - *ref_0
data_retention_hours: '24'
check_interval_minutes: '15'
mail:
  smtp:
    host: smtp.gmail.com
    port: '587'
    username: null
    password: null
  send_from: null
  enabled: false
secret: supersecretkey
