services:
  - name: Websiteee
    description: The main website for Tornado Emergency.
    url: https://tornadoemergency.net
    hide_url: false
    expected_response_code: 201
  - name: API
    description: The API for Tornado Emergency.
    url: https://timmygstudios.com
    hide_url: true
    expected_response_code: 201
data_retention_days: '30'
check_interval_seconds: '300'
secret: supersecretkey
