categories:
  - name: Web Services
    description: All web-related services
    services:
      - name: Wikipedia
        description: The site with all the cool stuffs
        url: https://en.wikipedia.org/wiki/Main_Page
        hide_url: false
        expected_response_code: 200
  - name: API Stuff
    description: API backend stuff you nerds wouldn't know about
    services:
      - name: HTTP BIN
        description: API GET Endpoint for HTTPBIN
        url: https://httpbin.org/get
        hide_url: false
        expected_response_code: 200
      - name: Javascript
        description: Broken Test Endpoint
        url: https://whatinthebrokenwebsiteisthis.com
        hide_url: true
        expected_response_code: 200
data_retention_hours: '24'
check_interval_minutes: '15'
name: OS Status
mail:
  smtp:
    host: smtp.gmail.com
    port: '587'
    username: ''
    password: ''
  send_from: ''
  enabled: false
secret: supersecretkey
