version: "3.8"

services:
  app:
    image: oven/bun:latest
    volumes:
      - .:/app # Mount the current directory to /app in the container
    working_dir: /app # Set the working directory
    command: bun start # Run the command
    ports:
      - "3000:3000" # Expose and map port 3000
